### ISSUE TITLE
Gunicorn won't start

### ISSUE THREAD

**Issue by larsmans** [beeldengeluid/AVResearcherXL#2]
I can't get Gunicorn to start AVResearcherXL;

```
$ gunicorn --log-level=debug --bind 0.0.0.0 avresearcher:app
```

produces

```
Traceback (most recent call last):
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/lars/src/AVResearcherXL/env/lib/python2.7/site-packages/gunicorn/util.py", line 374, in import_app
    raise AppImportError("Application object must be callable.")
AppImportError: Application object must be callable.

Application object must be callable.
[2015-02-27 15:46:55 +0000] [8849] [INFO] Worker exiting (pid: 8849)
[2015-02-27 15:46:55 +0000] [8844] [INFO] Shutting down: Master
[2015-02-27 15:46:55 +0000] [8844] [INFO] Reason: App failed to load.
```

This is Gunicorn 19.2.1, maybe you're using a different version? `python manage.py runserver` seems to work fine.

**Comment by justinvw** [comment]
The example in the README is no longer correct. You should be able to start the application via Gunicorn by running the following from the root of the repo:

```
$ gunicorn --log-level=debug --bind 0.0.0.0 wsgi:app
```

**Comment by larsmans** [comment]
Yep, that seems to work.

**Comment by krlakshmikanth** [comment]
> The example in the README is no longer correct. You should be able to start the application via Gunicorn by running the following from the root of the repo:
> 
> ```
> $ gunicorn --log-level=debug --bind 0.0.0.0 wsgi:app
> ```

Yes. It worked for me!
